/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.test3;

public class App {
  public String getGreeting() {
    return "줄리에가 아니라 줄리입니다";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println("이 코드는 영국으로부터 시작되었으며, 옛날옛날에 자바를 사용하는 꼬마가"
        + "살고있었어요.");
    
    System.out.println("하하핳....");
    System.out.println("하하핳2....");
    System.out.println("하하핳3....");
    System.out.println("이게 머선129");
    System.out.println("abcdef");
    System.out.println("아아아아아아아아");
    System.out.println("아아아아ㅏㅇ아아아아아아아아");
    System.out.println("으아아아아");
    System.out.println("ghijklmnop");
    System.out.println("qrstuvwxyz");
    System.out.println("푸쉬 한번하기 너무 힘들어요. 계속 충돌나요ㅕ");
    System.out.println("살려줘요");
    System.out.println("제 이름은 줄리입니다. 줄리에가 아니라");
    System.out.println("김승원입니다");
  }
}
